// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkg7xatWKGM9wb404JI8-EXYPRhfJXaI',
    appId: '1:1065315484955:web:415df15de6d0a221333fbe',
    messagingSenderId: '1065315484955',
    projectId: 'studyapp-c27ad',
    authDomain: 'studyapp-c27ad.firebaseapp.com',
    storageBucket: 'studyapp-c27ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgtQGNAYR7Qvqgi8J6RgG4NIgJforPqw',
    appId: '1:1065315484955:android:43af92f57eb999f9333fbe',
    messagingSenderId: '1065315484955',
    projectId: 'studyapp-c27ad',
    storageBucket: 'studyapp-c27ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleceMZ9pJokkMmTgP8CbKwDLmE3K0Y9Q',
    appId: '1:1065315484955:ios:d4e77bc051aa5e14333fbe',
    messagingSenderId: '1065315484955',
    projectId: 'studyapp-c27ad',
    storageBucket: 'studyapp-c27ad.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDleceMZ9pJokkMmTgP8CbKwDLmE3K0Y9Q',
    appId: '1:1065315484955:ios:26d6e178f6f9998b333fbe',
    messagingSenderId: '1065315484955',
    projectId: 'studyapp-c27ad',
    storageBucket: 'studyapp-c27ad.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
